# Digital Ocean App Platform Configuration
# Deploy with: doctl apps create --spec .do/app.yaml

name: traditional-swedish-fika
region: nyc

services:
  - name: backend
    source_dir: /backend
    github:
      repo: YOUR_GITHUB_USERNAME/traditional-swedish-fika
      branch: main
      deploy_on_push: true
    run_command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      
    envs:
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: ${db.CONNECTION_URL}
      - key: REDIS_URL
        value: ${redis.CONNECTION_URL}
      - key: SUPABASE_URL
        value: YOUR_SUPABASE_URL
        type: SECRET
      - key: SUPABASE_ANON_KEY
        value: YOUR_SUPABASE_ANON_KEY
        type: SECRET
      - key: OPENROUTER_API_KEY
        value: YOUR_OPENROUTER_API_KEY
        type: SECRET
      - key: UPSTASH_REDIS_URL
        value: YOUR_UPSTASH_REDIS_URL
        type: SECRET
      - key: UPSTASH_REDIS_TOKEN
        value: YOUR_UPSTASH_REDIS_TOKEN
        type: SECRET
        
  - name: frontend
    source_dir: /frontend
    github:
      repo: YOUR_GITHUB_USERNAME/traditional-swedish-fika
      branch: main
      deploy_on_push: true
    run_command: python -m http.server 3000 --directory /app
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    
    routes:
      - path: /static
      - path: /

databases:
  - name: fika-db
    engine: PG
    version: "15"
    size: basic
    num_nodes: 1

workers:
  - name: redis
    source_dir: /
    github:
      repo: YOUR_GITHUB_USERNAME/traditional-swedish-fika
      branch: main
    run_command: redis-server
    environment_slug: ubuntu
    instance_count: 1
    instance_size_slug: basic-xxs

alerts:
  - rule: CPU_UTILIZATION
    disabled: false
    value: 80
    operator: GREATER_THAN
    window: 5m
    emails: ["YOUR_EMAIL@example.com"]